### ISSUE TITLE
Function Name Prediction

### ISSUE THREAD

**Issue by SjRNMzU** [CMUSTRUDEL/DIRE#9]
Hi, I'm reading the source code and struggeling to see if I can use DIRE to predict the names of functions.

Is this possible and what would be the best way to achieve this? 

Thanks.

**Comment by jlacomis** [comment]
Sorry, but function name prediction was not one of the features that we built into DIRE. Conceptually, it is possible, but I actually think the DIRE approach would be overkill for that task.
